version: "3.8"

services:
  pitemp:
    container_name: pitemp
    image: icemarkom/pitemp:armhf
    volumes:
      - type: bind
        source: /root/temperature
        target: /thermal_source
    command:
      --thermal_file=/thermal_source
    ports:
      - 9550:9550
    networks:
      - pitemp
    restart: always

networks:
  pitemp:
    name: pitemp
